#!/bin/bash
#run only from terminal
if [ ! -t 0 ]; then "$TE" "$0"; exit; fi
IFS=$(echo -en "\n\b")
shopt -s nocaseglob

if [[ "$1" == help ]] || [[ "$1" == -h ]] || [[ "$1" == --help ]]; then
	echo "Render using an alternate title."
	echo
	echo "   Usage: "$(basename "$0")" alternate_title <warpmarkers> <settings>"
	echo
	echo "The default inputs are .warpmarkers and .settings. Outputs will be placed in test."
	exit
fi

if [[ -f test ]]; then
	echo "Error: A file called test exists."
	exit 1
fi

alternate_title="$1"
warpmarkers_file="${2:-"$(ls .warpmarkers *.warpmarkers 2>/dev/null | head -n 1)"}"
settings_file="${3:-"$(ls .settings *.settings 2>/dev/null | head -n 1)"}"

mkdir -p test/"$(dirname "$alternate_title")"

cp -f "$warpmarkers_file" test/"$alternate_title".warpmarkers
cp -f "$settings_file" test/"$alternate_title".settings

sed -i "s|title=.*|title=\"test\/$alternate_title\"|" test/"$alternate_title".settings

"$(dirname "$0")"/warptempo test/"$alternate_title".warpmarkers test/"$alternate_title".settings











