#!/bin/bash
#run only from terminal
if [ ! -t 0 ]; then exit; fi
shopt -s nocaseglob
set -e

if [[ "$1" == help ]] || [[ "$1" == -h ]] || [[ "$1" == --help ]]; then
	echo "Remove trim points."
	echo
	echo "   Usage: "$(basename "$0")" <warpmarkers>"
	echo
	echo "The default inputs are .warpmarkers and .settings."
	exit
fi

input_file="${1:-"$(ls .warpmarkers *.warpmarkers 2>/dev/null | head -n 1)"}"

validation_errors=0

if [[ ! -f "$input_file" ]]; then
	echo "Error: Input file does not exist" && ((validation_errors++))
fi

if [[ $validation_errors -gt 0 ]]; then
	exit 1
fi

sed -i 's/b=//g' "$input_file"
sed -i 's/begin_time=//g' "$input_file"
sed -i 's/e=//g' "$input_file"
sed -i 's/end_time=//g' "$input_file"

