#!/bin/bash
#run only from terminal
if [ ! -t 0 ]; then exit; fi
shopt -s nocaseglob
set -e

if [[ "$1" == help ]] || [[ "$1" == -h ]] || [[ "$1" == --help ]]; then
	echo "Flatten warp markers."
	echo
	echo "   Usage: "$(basename "$0")" <warpmarkers>"
	echo
	echo "The default input is .warpmarkers."
	exit
fi

input_file="${1:-"$(ls .warpmarkers *.warpmarkers 2>/dev/null | head -n 1)"}"
output_file="${input_file}.flattened"

validation_errors=0

if [[ ! -f "$input_file" ]]; then
	echo "Error: Input file does not exist" && ((validation_errors++))
fi

if [[ $validation_errors -gt 0 ]]; then
	exit 1
fi

rm -f "$output_file"

while IFS= read -r line; do
	if [[ "$line" == *\ * ]]; then
		comment="${line#* }"
		line="${line%% *}"
	else
		line="$line"
		comment=
	fi
	
	if [[ "$line" =~ [+-][A-Z] ]]; then
		echo "Error: ± followed by a capital letter found ($line)." && rm -f "$output_file" && exit 1
	fi
	
	commented_out=false
	
	if [[ "$line" == \#* ]]; then
		commented_out=true
		line="${line#\#}"
	fi
	
	is_variable_name=false
	variable_name=
	if [[ "$line" == begin_time=* ]] || [[ "$line" == b=* ]] || [[ "$line" == end_time=* ]] || [[ "$line" == e=* ]]; then
		is_variable_name=true
		variable_name="${line%%=*}"
		line="${line#*=}"
	fi
	
	if [[ "$line" != ??:??.???*\|?.??* ]] && [[ "$line" != ??:??.???*\|'""""'* ]]; then
		new_line="$line"
		
		if [[ ! -z "$comment" ]]; then
			new_line="$new_line $comment"
		fi
		
		if $is_variable_name; then
			new_line="${variable_name}=${new_line}"
		fi
		
		if $commented_out; then
			new_line="#$new_line"
		fi
		
		echo "$new_line" >> "$output_file"
		continue
	fi
	
	if [[ "$line" == *\|*\|* ]]; then
		time="$(echo "$line" | cut -d \| -f1)"
		tempo="$(echo "$line" | cut -d \| -f2)"
		label="$(echo "$line" | cut -d \| -f3)"
	elif [[ "$line" == *\|* ]]; then
		time="$(echo "$line" | cut -d \| -f1)"
		tempo="$(echo "$line" | cut -d \| -f2)"
		label=
	fi
	
	#flatten time
	if [[ "$time" == ??:??.???+* ]] || [[ "$time" == ??:??.???-* ]]; then
		time_initial="${time:0:9}"
		sign="${time:9:1}"
		time_offset="${time:10}"
		
		if [[ ! "$time_initial" =~ ^([0-5][0-9]):([0-5][0-9])\.[0-9]{3}$ ]]; then
			echo "Error: Invalid time format - use MM:SS.mmm ($line)." && rm -f "$output_file" && exit 1
		fi
		
		if [[ ! "$time_offset" =~ ^([0-9]{1,2}\.[0-9]{3})([+-][0-9]{1,2}\.[0-9]{3})*$ ]]; then
			echo "Error: Invalid time offset format - use S.mmm(±S.mmm) or SS.mmm(±SS.mmm) ($line)." && rm -f "$output_file" && exit 1
		fi
		
		seconds_initial="$(echo "$time_initial" | awk -F: '{ print ($1 * 60) + $2 }')"
		seconds_offset="$time_offset"
		seconds_total="$(echo "${seconds_initial}${sign}${seconds_offset}" | bc -l)"
		time=$(echo $(date -d@$(printf "%.3f\n" $seconds_total) -u +%M:%S.%N) | cut -c1-9)
	fi
	
	#flatten tempo
	if [[ "$tempo" == [0-9]* ]]; then
		if [[ ! "$tempo" =~ ^([0-9]\.[0-9]{2}([+-][0-9]\.[0-9]{2})*)(\*[0-9]\.[0-9]{4})?$ ]]; then
			echo "Error: Invalid tempo format - use 1.00(±0.01) or 1.00(±0.01)*1.0000, etc. Addition and subtraction will be performed before multiplication. Examples: 1.00, 1.00+0.01-0.02, 1.00*1.0000, 1.00+0.01-0.02*1.0000 ($line)." && rm -f "$output_file" && exit 1
		fi
		if [[ "$tempo" == *\** ]]; then
			tempo_initial="${tempo%\**}"
			tempo_initial="$(printf "%.2f\n" "$(echo "$tempo_initial" | bc -l)")"
			tempo_scale="${tempo#*\*}"
			tempo="${tempo_initial}*${tempo_scale}"
		else
			tempo="$(printf "%.2f\n" "$(echo "$tempo" | bc -l)")"
		fi
	fi
	
	new_line="$time|$tempo"
	
	if [[ ! -z "$label" ]]; then
		if [[ ! "$label" =~ ^[a-z]\.[a-z0-9]{2}$ ]]; then
			echo "Error: Invalid label - use a.01, b.2b, etc. First character must be a lowercase letter, followed by a period, then any two lowercase letters or digits. Use a hash symbol before the declaration of the label (ie, when the label is declared after a tempo value) to disable all warp markers with that label ($line)." && rm -f "$output_file" && exit 1
		fi
		new_line="$new_line|$label"
	fi
	
	if [[ ! -z "$comment" ]]; then
		new_line="$new_line $comment"
	fi
	
	if $is_variable_name; then
		new_line="${variable_name}=${new_line}"
	fi
	
	if $commented_out; then
		new_line="#$new_line"
	fi
	
	echo "$new_line" >> "$output_file"
	
done < "$input_file" && \
mv "$input_file" "$input_file"~ && \
mv "$output_file" "$input_file"
















